var treeData = [
  {
    "address": "",
    "name": "尚阳科技",
    "id": 150,
    "description": "",
    "sort": 3,
    "pid": 0,
    "parentName": null,
    "uSNCreated": "12724",
    "levels": "OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180710034811.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "研发部",
    "id": 151,
    "description": "",
    "sort": 1,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "12729",
    "levels": "OU=研发部,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180710034811.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "测试组",
    "id": 152,
    "description": "",
    "sort": 2,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "41111",
    "levels": "OU=测试组,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180929014621.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "总公司",
    "id": 153,
    "description": "",
    "sort": 3,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "61097",
    "levels": "OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930090755.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "数据中心",
    "id": 154,
    "description": "",
    "sort": 4,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "41109",
    "levels": "OU=数据中心,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930071612.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "广州平台",
    "id": 155,
    "description": "",
    "sort": 5,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "42429",
    "levels": "OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072455.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "上海分公司",
    "id": 156,
    "description": "",
    "sort": 6,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "42448",
    "levels": "OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930075054.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "深圳分公司",
    "id": 157,
    "description": "",
    "sort": 7,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "270037",
    "levels": "OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072848.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "特殊邮箱用户",
    "id": 158,
    "description": "",
    "sort": 8,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "408743",
    "levels": "OU=特殊邮箱用户,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181126015021.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "特殊邮箱联系组",
    "id": 159,
    "description": "",
    "sort": 9,
    "pid": 150,
    "parentName": null,
    "uSNCreated": "408741",
    "levels": "OU=特殊邮箱联系组,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181126015004.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "测试一",
    "id": 160,
    "description": "",
    "sort": 1,
    "pid": 152,
    "parentName": null,
    "uSNCreated": "41114",
    "levels": "OU=测试一,OU=测试组,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008065535.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "人事部",
    "id": 161,
    "description": "",
    "sort": 1,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "135155",
    "levels": "OU=人事部,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930092543.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "管理部",
    "id": 162,
    "description": "",
    "sort": 2,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "135158",
    "levels": "OU=管理部,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930093937.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "采购部",
    "id": 163,
    "description": "",
    "sort": 3,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "135160",
    "levels": "OU=采购部,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930090818.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "产权部",
    "id": 164,
    "description": "",
    "sort": 4,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "135162",
    "levels": "OU=产权部,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930093021.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "客服部",
    "id": 165,
    "description": "",
    "sort": 5,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "408344",
    "levels": "OU=客服部,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181122054502.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "信息部1",
    "id": 173,
    "description": "",
    "sort": 6,
    "pid": 153,
    "parentName": null,
    "uSNCreated": "135164",
    "levels": "OU=信息部1,OU=总公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181114071958.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "信息部",
    "id": 166,
    "description": "",
    "sort": 1,
    "pid": 154,
    "parentName": null,
    "uSNCreated": "41830",
    "levels": "OU=信息部,OU=数据中心,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930071612.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "商务部",
    "id": 172,
    "description": "",
    "sort": 2,
    "pid": 154,
    "parentName": null,
    "uSNCreated": "49065",
    "levels": "OU=商务部,OU=数据中心,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930075851.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "华南区",
    "id": 167,
    "description": "",
    "sort": 1,
    "pid": 155,
    "parentName": null,
    "uSNCreated": "42431",
    "levels": "OU=华南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072509.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "东南区",
    "id": 168,
    "description": "",
    "sort": 2,
    "pid": 155,
    "parentName": null,
    "uSNCreated": "42440",
    "levels": "OU=东南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072604.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "西北区",
    "id": 169,
    "description": "",
    "sort": 3,
    "pid": 155,
    "parentName": null,
    "uSNCreated": "42446",
    "levels": "OU=西北区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072651.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "西南区",
    "id": 170,
    "description": "",
    "sort": 4,
    "pid": 155,
    "parentName": null,
    "uSNCreated": "42450",
    "levels": "OU=西南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072719.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "华中区",
    "id": 171,
    "description": "",
    "sort": 5,
    "pid": 155,
    "parentName": null,
    "uSNCreated": "42453",
    "levels": "OU=华中区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072815.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "财务部",
    "id": 179,
    "description": "",
    "sort": 1,
    "pid": 156,
    "parentName": null,
    "uSNCreated": "43058",
    "levels": "OU=财务部,OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930075054.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "行政部",
    "id": 180,
    "description": "",
    "sort": 2,
    "pid": 156,
    "parentName": null,
    "uSNCreated": "61099",
    "levels": "OU=行政部,OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930083847.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "客服部",
    "id": 181,
    "description": "",
    "sort": 3,
    "pid": 156,
    "parentName": null,
    "uSNCreated": "135166",
    "levels": "OU=客服部,OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930091008.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "销售部",
    "id": 182,
    "description": "",
    "sort": 4,
    "pid": 156,
    "parentName": null,
    "uSNCreated": "135168",
    "levels": "OU=销售部,OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930090913.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "运维部",
    "id": 183,
    "description": "",
    "sort": 5,
    "pid": 156,
    "parentName": null,
    "uSNCreated": "135170",
    "levels": "OU=运维部,OU=上海分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930090941.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "一部",
    "id": 174,
    "description": "",
    "sort": 1,
    "pid": 157,
    "parentName": null,
    "uSNCreated": "270039",
    "levels": "OU=一部,OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072848.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "二部",
    "id": 175,
    "description": "",
    "sort": 2,
    "pid": 157,
    "parentName": null,
    "uSNCreated": "270042",
    "levels": "OU=二部,OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072859.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "三部",
    "id": 176,
    "description": "",
    "sort": 3,
    "pid": 157,
    "parentName": null,
    "uSNCreated": "270044",
    "levels": "OU=三部,OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072908.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "四部",
    "id": 177,
    "description": "",
    "sort": 4,
    "pid": 157,
    "parentName": null,
    "uSNCreated": "270046",
    "levels": "OU=四部,OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072921.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "五部",
    "id": 178,
    "description": "",
    "sort": 5,
    "pid": 157,
    "parentName": null,
    "uSNCreated": "270048",
    "levels": "OU=五部,OU=深圳分公司,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008072936.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "组一",
    "id": 184,
    "description": "",
    "sort": 1,
    "pid": 160,
    "parentName": null,
    "uSNCreated": "258031",
    "levels": "OU=组一,OU=测试一,OU=测试组,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008065846.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "组二",
    "id": 185,
    "description": "",
    "sort": 2,
    "pid": 160,
    "parentName": null,
    "uSNCreated": "258035",
    "levels": "OU=组二,OU=测试一,OU=测试组,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20181008065858.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "湖北",
    "id": 186,
    "description": "",
    "sort": 1,
    "pid": 167,
    "parentName": null,
    "uSNCreated": "42434",
    "levels": "OU=湖北,OU=华南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072520.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "福建",
    "id": 187,
    "description": "",
    "sort": 1,
    "pid": 168,
    "parentName": null,
    "uSNCreated": "42442",
    "levels": "OU=福建,OU=东南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072636.0Z",
    "zipCode": "",
    "isParent": false
  },
  {
    "address": "",
    "name": "武汉",
    "id": 188,
    "description": "",
    "sort": 1,
    "pid": 186,
    "parentName": null,
    "uSNCreated": "42437",
    "levels": "OU=武汉,OU=湖北,OU=华南区,OU=广州平台,OU=尚阳科技,DC=yftest,DC=com,DC=cn",
    "phone": "",
    "isEnable": 1,
    "isDelete": 1,
    "whenChanged": "20180930072520.0Z",
    "zipCode": "",
    "isParent": false
  }
];
